# Generated by Django 5.2 on 2026-05-07 19:43

import django.db.models.deletion
import email_relay.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_relay', '0002_auto_20231030_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('mimetype', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(upload_to=email_relay.models.attachment_upload_to)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='email_relay.message')),
            ],
        ),
    ]
