# Generated by Django 5.2 on 2026-08-11 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_relay', '0002_auto_20231030_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('kind', models.CharField(choices=[('bytes', 'Bytes'), ('mime', 'MIME')], max_length=16)),
                ('filename', models.TextField(blank=True, null=True)),
                ('content_type', models.TextField()),
                ('content', models.BinaryField()),
                ('size', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='email_relay.message')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('message', 'position'), name='email_relay_msgattach_pos_uniq')],
            },
        ),
    ]
