# Generated by Django 5.2 on 2026-05-07 20:42

import base64
import binascii
import uuid

from django.core.files.base import ContentFile
from django.core.files.storage import default_storage
from django.db import migrations


def attachment_content_bytes(attachment):
    content = attachment.get("content", "")
    encoding = attachment.get("encoding")
    mimetype = attachment.get("mimetype", "")

    if encoding == "base64":
        return base64.b64decode(content, validate=True)

    if encoding == "text" or mimetype.startswith("text/"):
        return content.encode("utf-8")

    try:
        return base64.b64decode(content, validate=True)
    except (binascii.Error, ValueError):
        return content.encode("utf-8")


def migrate_attachments_to_files(apps, schema_editor):
    Message = apps.get_model("email_relay", "Message")
    MessageAttachment = apps.get_model("email_relay", "MessageAttachment")

    for message in Message.objects.all():
        data = dict(message.data or {})
        attachments = data.pop("attachments", [])
        if not attachments:
            continue

        for attachment in attachments:
            filename = attachment.get("filename", "") or "attachment"
            storage_path = f"email-relay/attachments/{message.pk}/{uuid.uuid4()}-{filename}"
            storage_name = default_storage.save(
                storage_path,
                ContentFile(attachment_content_bytes(attachment)),
            )
            MessageAttachment.objects.create(
                message=message,
                filename=filename,
                mimetype=attachment.get("mimetype", ""),
                file=storage_name,
            )

        message.data = data
        message.save(update_fields=["data"])


class Migration(migrations.Migration):
    dependencies = [
        ("email_relay", "0003_messageattachment"),
    ]

    operations = [
        migrations.RunPython(migrate_attachments_to_files, migrations.RunPython.noop),
    ]
