# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v2024.18
_src_path: gh:westerveltco/django-twc-package
author_email: josh@joshthomas.dev
author_name: Josh Thomas
current_version: 0.6.0
django_versions:
- '5.2'
- '6.0'
- '6.1'
docs_domain: westervelt.dev
github_owner: westerveltco
github_repo: django-email-relay
module_name: email_relay
package_description: Centralize and relay email from multiple distributed Django projects
    to an internal SMTP server via a database queue.
package_name: django-email-relay
python_versions:
- '3.10'
- '3.11'
- '3.12'
- '3.13'
- '3.14'
test_django_main: true
versioning_scheme: SemVer
